# Imports

In [49]:
#install Vader through "pip install vaderSentiment" in terminal
#install NLTK through "pip install user -U nltk"
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import nltk
from scipy import stats
nltk.download('punkt')  # Required for TextBlob tokenization
nltk.download('averaged_perceptron_tagger')  # Required for TextBlob
from textblob import TextBlob
from scipy import stats
import numpy as np
df = pd.read_csv('../../Data/2. IntermediateData/df_binarized_hard.csv')

[nltk_data] Downloading package punkt to /Users/brookeye/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/brookeye/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

In [35]:
df

,utterance_id,conversation_id,text,speaker,movie_id,reply_to,speaker_id,character_name,movie_id.1,title,...,credit_pos,year,id,imdbid,bechdel_score,imdb_score,numVotes,runtimeMinutes,genres,oscar
0,L1045,L1044,They do not!,u0,m0,L1044,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
1,L1044,L1044,They do to!,u2,m0,NaN,u2,CAMERON,m0,10 things i hate about you,...,3,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
2,L985,L984,I hope so.,u0,m0,L984,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
3,L984,L984,She okay?,u2,m0,NaN,u2,CAMERON,m0,10 things i hate about you,...,3,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
4,L925,L924,Let's go.,u0,m0,L924,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137057,L665991,L665987,"I'm sorry, sir. We only seat by reservation.",u9021,m615,L665990,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137058,L665990,L665987,Food!!,u9023,m615,L665989,u9023,MONSTER,m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137059,L665989,L665987,Do you have a reservation?,u9021,m615,L665988,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137060,L665988,L665987,Food!,u9023,m615,L665987,u9023,MONSTER,m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137061,L665987,L665987,"Yes, sir, name, please?",u9021,m615,NaN,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0

In [36]:
df=df.drop(['movie_id.1'], axis=1)

# Textblob (exploratory). Conclusion: Unreliable

# Calculating sentiment score with VADER (DF_Hard)

In [37]:
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get polarity scores
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

# Apply sentiment analysis to each line of dialogue
df['sentiment'] = df['text'].apply(get_sentiment)

# 1. Mean sentiment polarity by gender overall
mean_sentiment_by_gender = df.groupby('gender')['sentiment'].mean()

# 2. Mean sentiment polarity by gender split by Bechdel score
mean_sentiment_by_gender_bechdel = df.groupby(['bechdel_score', 'gender'])['sentiment'].mean()

# To present it more clearly, you can unstack the results
mean_sentiment_split = mean_sentiment_by_gender_bechdel.unstack()

print("Overall mean sentiment by gender:")
print(mean_sentiment_by_gender)

print("\nMean sentiment by gender and Bechdel score:")
print(mean_sentiment_split)

Overall mean sentiment by gender:
gender
f    0.058220
m    0.048871
Name: sentiment, dtype: float64

Mean sentiment by gender and Bechdel score:
gender                f         m
bechdel_score
0              0.058090  0.044079
1              0.058289  0.055099

In [38]:
df

,utterance_id,conversation_id,text,speaker,movie_id,reply_to,speaker_id,character_name,title,gender,...,year,id,imdbid,bechdel_score,imdb_score,numVotes,runtimeMinutes,genres,oscar,sentiment
0,L1045,L1044,They do not!,u0,m0,L1044,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
1,L1044,L1044,They do to!,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
2,L985,L984,I hope so.,u0,m0,L984,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.4404
3,L984,L984,She okay?,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.2263
4,L925,L924,Let's go.,u0,m0,L924,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137057,L665991,L665987,"I'm sorry, sir. We only seat by reservation.",u9021,m615,L665990,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,-0.0772
137058,L665990,L665987,Food!!,u9023,m615,L665989,u9023,MONSTER,young frankenstein,m,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137059,L665989,L665987,Do you have a reservation?,u9021,m615,L665988,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137060,L665988,L665987,Food!,u9023,m615,L665987,u9023,MONSTER,young frankenstein,m,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137061,L665987,L665987,"Yes, sir, name, please?",u9021,m615,NaN,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.6124

In [51]:
# Initialize analyzer
analyzer = SentimentIntensityAnalyzer()
df['sentiment'] = df['text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

# Function for Cohen's d
def cohens_d(group1, group2):
    n1, n2 = len(group1), len(group2)
    pooled_std = np.sqrt(((n1-1)*group1.std()**2 + (n2-1)*group2.std()**2) / (n1 + n2 - 2))
    return abs((group1.mean() - group2.mean()) / pooled_std)

# ===== 1. Gender Differences =====
male_all = df[df['gender'] == 'm']['sentiment']
female_all = df[df['gender'] == 'f']['sentiment']
t_gender, p_gender = stats.ttest_ind(female_all, male_all, equal_var=False)

print("="*50)
print("GENDER DIFFERENCES (OVERALL)")
print(f"Female mean: {female_all.mean():.3f} | Male mean: {male_all.mean():.3f}")
print(f"t = {t_gender:.2f}, p = {p_gender:.10f} {'***' if p_gender < 0.001 else '**' if p_gender < 0.01 else '*' if p_gender < 0.05 else 'ns'}")
print(f"Effect size (Cohen's d): {cohens_d(female_all, male_all):.2f}")

# ===== 2. Gender Differences by Bechdel =====
print("\n" + "="*50)
print("GENDER DIFFERENCES BY BECHDEL SCORE")

for bechdel in [0, 1]:
    female = df[(df['gender']=='f') & (df['bechdel_score']==bechdel)]['sentiment']
    male = df[(df['gender']=='m') & (df['bechdel_score']==bechdel)]['sentiment']
    t, p = stats.ttest_ind(female, male, equal_var=False)
    
    print(f"\nBECHDEL {bechdel}:")
    print(f"Female mean: {female.mean():.3f} | Male mean: {male.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.10f} {'***' if p < 0.000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(female, male):.2f}")

# ===== 3. Bechdel Differences by Gender =====
print("\n" + "="*50)
print("BECHDEL DIFFERENCES BY GENDER")

for gender in ['f', 'm']:
    bechdel1 = df[(df['gender']==gender) & (df['bechdel_score']==1)]['sentiment']
    bechdel0 = df[(df['gender']==gender) & (df['bechdel_score']==0)]['sentiment']
    t, p = stats.ttest_ind(bechdel1, bechdel0, equal_var=False)
    
    print(f"\n{gender.upper()} DIALOGUE:")
    print(f"Bechdel 1 mean: {bechdel1.mean():.3f} | Bechdel 0 mean: {bechdel0.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.10f} {'***' if p < 0.00000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(bechdel1, bechdel0):.2f}")

# ===== 4. Sample Sizes =====
print("\n" + "="*50)
print("SAMPLE SIZES")
print(f"Total female: {len(female_all)} | Total male: {len(male_all)}")
print("\nBy Bechdel Score:")
for bechdel in [0, 1]:
    print(f"Bechdel {bechdel} - Female: {len(df[(df['gender']=='f') & (df['bechdel_score']==bechdel)])} | Male: {len(df[(df['gender']=='m') & (df['bechdel_score']==bechdel)])}")

==================================================
GENDER DIFFERENCES (OVERALL)
Female mean: 0.058 | Male mean: 0.049
t = 4.72, p = 0.0000023399 ***
Effect size (Cohen's d): 0.03

==================================================
GENDER DIFFERENCES BY BECHDEL SCORE

BECHDEL 0:
Female mean: 0.058 | Male mean: 0.044
t = 4.51, p = 0.0000065357 **
Effect size: 0.04

BECHDEL 1:
Female mean: 0.058 | Male mean: 0.055
t = 1.19, p = 0.2322788612 ns
Effect size: 0.01

==================================================
BECHDEL DIFFERENCES BY GENDER

F DIALOGUE:
Bechdel 1 mean: 0.058 | Bechdel 0 mean: 0.058
t = 0.06, p = 0.9531287151 ns
Effect size: 0.00

M DIALOGUE:
Bechdel 1 mean: 0.055 | Bechdel 0 mean: 0.044
t = 4.77, p = 0.0000018184 **
Effect size: 0.03

==================================================
SAMPLE SIZES
Total female: 44695 | Total male: 92367

By Bechdel Score:
Bechdel 0 - Female: 15459 | Male: 52201
Bechdel 1 - Female: 29236 | Male: 40166

### Trying to do intensity (aboluste value). Results inconclusive

In [43]:
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get ABSOLUTE polarity scores (intensity)
def get_sentiment_intensity(text):
    return abs(analyzer.polarity_scores(text)['compound'])  # Absolute value for intensity

# Apply sentiment intensity analysis to each line of dialogue
df['sentiment_intensity'] = df['text'].apply(get_sentiment_intensity)

# 1. Mean sentiment intensity by gender overall
mean_intensity_by_gender = df.groupby('gender')['sentiment_intensity'].mean()

# 2. Mean sentiment intensity by gender split by Bechdel score
mean_intensity_by_gender_bechdel = df.groupby(['bechdel_score', 'gender'])['sentiment_intensity'].mean()

# Unstack for clearer presentation
mean_intensity_split = mean_intensity_by_gender_bechdel.unstack()

print("Overall mean sentiment INTENSITY (absolute polarity) by gender:")
print(mean_intensity_by_gender)

print("\nMean sentiment INTENSITY by gender and Bechdel score:")
print(mean_intensity_split)

Overall mean sentiment INTENSITY (absolute polarity) by gender:
gender
f    0.224141
m    0.225896
Name: sentiment_intensity, dtype: float64

Mean sentiment INTENSITY by gender and Bechdel score:
gender                f         m
bechdel_score
0              0.219504  0.221201
1              0.226593  0.231998

In [44]:
df

,utterance_id,conversation_id,text,speaker,movie_id,reply_to,speaker_id,character_name,title,gender,...,bechdel_score,imdb_score,numVotes,runtimeMinutes,genres,oscar,sentiment,sentiment_category,sentiment_textblob,sentiment_intensity
0,L1045,L1044,They do not!,u0,m0,L1044,u0,BIANCA,10 things i hate about you,f,...,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000,Neutral,0.00,0.0000
1,L1044,L1044,They do to!,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000,Neutral,0.00,0.0000
2,L985,L984,I hope so.,u0,m0,L984,u0,BIANCA,10 things i hate about you,f,...,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.4404,Neutral,0.00,0.4404
3,L984,L984,She okay?,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.2263,Positive,0.50,0.2263
4,L925,L924,Let's go.,u0,m0,L924,u0,BIANCA,10 things i hate about you,f,...,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000,Neutral,0.00,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137057,L665991,L665987,"I'm sorry, sir. We only seat by reservation.",u9021,m615,L665990,u9021,MAITRE D',young frankenstein,f,...,0,8.0,176404,106,Comedy,0,-0.0772,Negative,-0.25,0.0772
137058,L665990,L665987,Food!!,u9023,m615,L665989,u9023,MONSTER,young frankenstein,m,...,0,8.0,176404,106,Comedy,0,0.0000,Neutral,0.00,0.0000
137059,L665989,L665987,Do you have a reservation?,u9021,m615,L665988,u9021,MAITRE D',young frankenstein,f,...,0,8.0,176404,106,Comedy,0,0.0000,Neutral,0.00,0.0000
137060,L665988,L665987,Food!,u9023,m615,L665987,u9023,MONSTER,young frankenstein,m,...,0,8.0,176404,106,Comedy,0,0.0000,Neutral,0.00,0.0000
137061,L665987,L665987,"Yes, sir, name, please?",u9021,m615,NaN,u9021,MAITRE D',young frankenstein,f,...,0,8.0,176404,106,Comedy,0,0.6124,Neutral,0.00,0.6124

In [40]:

def get_sentiment_textblob(text):
    return TextBlob(text).sentiment.polarity  # Range: [-1, 1]

df['sentiment_textblob'] = df['text'].apply(get_sentiment_textblob)

# Compute means
print("\nOverall mean sentiment by gender (TextBlob):")
print(df.groupby('gender')['sentiment_textblob'].mean())

print("\nMean sentiment by Bechdel score and gender (TextBlob):")
print(df.groupby(['bechdel_score', 'gender'])['sentiment_textblob'].mean().unstack())

Overall mean sentiment by gender (TextBlob):
gender
f    0.039871
m    0.044765
Name: sentiment_textblob, dtype: float64

Mean sentiment by Bechdel score and gender (TextBlob):
gender                f         m
bechdel_score
0              0.041194  0.042875
1              0.039172  0.047223

In [42]:
# Categorize sentiment first
df['sentiment_category'] = df['sentiment_textblob'].apply(
    lambda x: 'Positive' if x >= 0.05 
    else 'Negative' if x <= -0.05 
    else 'Neutral'
)

# Print text for each category
print("="*50 + "\nFIRST 40 POSITIVE TEXTS\n" + "="*50)
for text in df[df['sentiment_category'] == 'Positive']['text'].head(200):
    print(text)
    print("-"*50)  # Separator between entries

# print("\n" + "="*50 + "\nFIRST 40 NEUTRAL TEXTS\n" + "="*50) 
# for text in df[df['sentiment_category'] == 'Neutral']['text'].head(40):
#     print(text)
#     print("-"*50)

print("\n" + "="*50 + "\nFIRST 40 NEGATIVE TEXTS\n" + "="*50)
for text in df[df['sentiment_category'] == 'Negative']['text'].head(200):
    print(text)
    print("-"*50)

==================================================
FIRST 40 POSITIVE TEXTS
==================================================
She okay?
--------------------------------------------------
Wow
--------------------------------------------------
Okay -- you're gonna need to learn how to lie.
--------------------------------------------------
The "real you".
--------------------------------------------------
What good stuff?
--------------------------------------------------
I figured you'd get to the good stuff eventually.
--------------------------------------------------
Thank God!  If I had to hear one more story about your coiffure...
--------------------------------------------------
Have fun tonight?
--------------------------------------------------
So that's the kind of guy she likes? Pretty ones?
--------------------------------------------------
Lesbian?  No. I found a picture of Jared Leto in one of her drawers, so I'm pretty sure she's not harboring same-sex tendencies.
--------------------------------------------------
I really, really, really wanna go, but I can't.  Not unless my sister goes.
--------------------------------------------------
Sure have.
--------------------------------------------------
You're sweet.
--------------------------------------------------
That's because it's such a nice one.
--------------------------------------------------
I don't want to know how to say that though.  I want to know useful things. Like where the good stores are.  How much does champagne cost?  Stuff like Chat.  I have never in my life had to point out my head to someone.
--------------------------------------------------
Right.  See?  You're ready for the quiz.
--------------------------------------------------
Seems like she could get a date easy enough...
--------------------------------------------------
The thing is, Cameron -- I'm at the mercy of a particularly hideous breed of loser.  My sister.  I can't date until she does.
--------------------------------------------------
You're asking me out.  That's so cute. What's your name again?
--------------------------------------------------
Okay... then how 'bout we try out some French cuisine.  Saturday?  Night?
--------------------------------------------------
Well, I thought we'd start with pronunciation, if that's okay with you.
--------------------------------------------------
Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.
--------------------------------------------------
Combination.  I don't know -- I thought he'd be different.  More of a gentleman...
--------------------------------------------------
He practically proposed when he found out we had the same dermatologist. I mean. Dr. Bonchowski is great an all, but he's not exactly relevant party conversation.
--------------------------------------------------
Great
--------------------------------------------------
Hey, sweet cheeks.
--------------------------------------------------
My agent says I've got a good shot at being the Prada guy next year.
--------------------------------------------------
It's a gay cruise line, but I'll be, like, wearing a uniform and stuff.
--------------------------------------------------
So yeah, I've got the Sears catalog thing going -- and the tube sock gig " that's gonna be huge.  And then I'm up for an ad for Queen Harry next week.
--------------------------------------------------
Exactly  So, you going to Bogey Lowenbrau's thing on Saturday?
--------------------------------------------------
It's more
--------------------------------------------------
Is that woman a complete fruit-loop or is it just me?
--------------------------------------------------
What? To completely damage me?  To send me to therapy forever? What?
--------------------------------------------------
You looked beautiful last night, you know.
--------------------------------------------------
Not all experiences are good, Bianca. You can't always trust the people you want to.
--------------------------------------------------
I'm not stupid enough to repeat your mistakes.
--------------------------------------------------
No. you didn't!  If you really thought I could make my own decisions, you would've let me go out with him instead of helping Daddy hold me hostage.
--------------------------------------------------
I wanted to let you make up your own mind about him.
--------------------------------------------------
After that, I swore I'd never do anything just because "everyone else" was doing it.  And I haven't since. Except for Bogey's party, and my stunning gastro-intestinal display --
--------------------------------------------------
Just once.  Afterwards, I told him I didn't want to anymore.  I wasn't ready. He got pissed.  Then he broke up with me.
--------------------------------------------------
I do care. But I'm a firm believer in doing something for your own reasons, not someone else ' s .
--------------------------------------------------
You're welcome.
--------------------------------------------------
I don't get you.  You act like you're too good for any of this, and then you go totally apeshit when you get here.
--------------------------------------------------
I really don't think I need any social advice from you right now.
--------------------------------------------------
You are so completely unbalanced.
--------------------------------------------------
Can't you forget for just one night that you're completely wretched?
--------------------------------------------------
Bogey Lowenstein's party is normal, but you're too busy listening to Bitches Who Need Prozac to know that.
--------------------------------------------------
What's normal?
--------------------------------------------------
You're ruining my life'  Because you won't be normal, I can't be normal.
--------------------------------------------------
Oh my God, does this mean you're becoming normal?
--------------------------------------------------
Fine.  I see that I'm a prisoner in my own house.  I'm not a daughter. I'm a possession!
--------------------------------------------------
It's that hot rod Joey, right? That ' s who you want me to bend my rules for?
--------------------------------------------------
Exactly my point
--------------------------------------------------
Best case scenario, you're back on the payroll for awhile.
--------------------------------------------------
The hell is that?  What kind of 'guy just picks up a girl and carries her away while you're talking to her?
--------------------------------------------------
Hell, I've just been going over the whole thing in my head and -
--------------------------------------------------
It's her favorite band.
--------------------------------------------------
Okay!  I wasn't sure
--------------------------------------------------
He's pretty!
--------------------------------------------------
Her favorite uncle
--------------------------------------------------
Are you kidding?  He'll piss himself with joy.  He's the ultimate kiss ass.
--------------------------------------------------
This is it.  A golden opportunity. Patrick can ask Katarina to the party.
--------------------------------------------------
Like we had a choice?  Besides -- when you let the enemy think he's orchestrating the battle, you're in a position of power. We let him pretend he's calling the shots, and while he's busy setting up the plan, you have time to woo Bianca.
--------------------------------------------------
I'm serious, man, he's whacked.  He sold his own liver on the black market so he could buy new speakers.
--------------------------------------------------
I teach her French, get to know her, dazzle her with charm and she falls in love with me.
--------------------------------------------------
Sure do ... my Mom's from Canada
--------------------------------------------------
Because they're bred to.  Their mothers liked guys like that, and their grandmothers before them. Their gene pool is rarely diluted.
--------------------------------------------------
I could start with your haircut, but it doesn't matter.  She's not allowed to date until her older sister does.  And that's an impossibility.
--------------------------------------------------
How many people go here?
--------------------------------------------------
How many people were in your old school?
--------------------------------------------------
I was kidding. People actually live there?
--------------------------------------------------
You the new guy?
--------------------------------------------------
She just needs time to cool off I'll give it a day.
--------------------------------------------------
She hates you with the fire of a thousand suns .  That's a direct quote
--------------------------------------------------
Sure
--------------------------------------------------
It's off. The whole thing.
--------------------------------------------------
I've retrieved certain pieces of information on Miss Katarina Stratford I think you'll find helpful.
--------------------------------------------------
Fine, thirty.
--------------------------------------------------
How much?
--------------------------------------------------
Sure, Sparky.  I'll get right on it.
--------------------------------------------------
Two legs, nice rack...
--------------------------------------------------
Hey -- it's all for the higher good right?
--------------------------------------------------
You better not fuck this up.  I'm heavily invested.
--------------------------------------------------
Uh,  yeah.  We're old friend*
--------------------------------------------------
Well, actually, I thought I'd run an idea by you.  You know, just to see if you're interested.
--------------------------------------------------
Oh, good.  Something new and different for us.
--------------------------------------------------
Okay, okay, we won't go.  It's not like I have a dress anyway
--------------------------------------------------
Listen to you!  You sound like Betty, all pissed off because Archie is taking Veronica.
--------------------------------------------------
If I was Bianca, it would be, "Any school you want, precious.  Don't forget your tiara."
--------------------------------------------------
William didn't even go to high school
--------------------------------------------------
So he has this huge raging fit about Sarah Lawrence and insists that I go to his male-dominated, puking frat boy, number one golf team school. I have no say at all.
--------------------------------------------------
You could always go with me.  I'm sure William has some friends.
--------------------------------------------------
The people at this school are so incredibly foul.
--------------------------------------------------
I'm sure he's completely incapable of doing anything that interesting.
--------------------------------------------------
Is that right?
--------------------------------------------------
Besides, I had some extra cash. Some asshole paid me to take out a really great girl.
--------------------------------------------------
That ' s completely adorable!
--------------------------------------------------
You're amazingly self-assured. Has anyone ever told you that?
--------------------------------------------------
You're sweet.  And sexy.  And completely hot for me.
--------------------------------------------------
No -- something real.  Something no one else knows.
--------------------------------------------------
Tell me something true.
--------------------------------------------------
You never disappointed me.
--------------------------------------------------
A soft side? Who knew?
--------------------------------------------------
Good call.
--------------------------------------------------
I figured it had to be something ridiculous to win your respect.  And piss you off.
--------------------------------------------------
Put your right foot there --
--------------------------------------------------
Pleasant?
--------------------------------------------------
He just wants me to be someone I'm not.
--------------------------------------------------
Busy
--------------------------------------------------
Hey man. . .  You don ' t think I can be "cool"?  You don't think I can be "laid back" like everyone else?
--------------------------------------------------
I know.  It'd have to be a pretty big deal to get you to mainline tequila. You don't seem like the type.
--------------------------------------------------
Sure, I do
--------------------------------------------------
I'm fine. I'm
--------------------------------------------------
Okay?
--------------------------------------------------
Funny, you're the only one
--------------------------------------------------
You know, these guys are no Bikini Kill or The Raincoats, but they're right up there.
--------------------------------------------------
hey.  Great show, huh?
--------------------------------------------------
Depends on the topic. My fenders don't really whip me into a verbal frenzy.
--------------------------------------------------
I don't really think you warrant that strong an emotion.
--------------------------------------------------
I know a lot more than that
--------------------------------------------------
Oh, right.  Friday.
--------------------------------------------------
You know, fathers don't like to admit that their daughters are capable of running their own lives.  It means we've become spectators.  Bianca still lets me play a few innings.  You've had me on the bleachers for years.  When you go to Sarah Lawrence, I won't even be able to watch the game.
--------------------------------------------------
So tell me about this dance. Was it fun?
--------------------------------------------------
Funny.
--------------------------------------------------
Yeah.  She left with some bikers Big ones.  Full of sperm.
--------------------------------------------------
I want to go to an East Coast school! I want you to trust me to make my own choices.  I want --
--------------------------------------------------
As a parent, that's my right
--------------------------------------------------
This from someone whose diary is devoted to favorite grooming tips?
--------------------------------------------------
Am I supposed to feel better? Like, right now?  Or do I have some time to think about it?
--------------------------------------------------
No ... I believe "heinous bitch" is the term used most often.
--------------------------------------------------
Well, yes, compared to your other choices of expression this year, today's events are quite mild.  By the way, Bobby Rictor's gonad retrieval operation went quite well, in case you're interested.
--------------------------------------------------
Expressing my opinion is not a terrorist action.
--------------------------------------------------
Right.
--------------------------------------------------
Macbeth, right?
--------------------------------------------------
Cool pictures.  You a fan?
--------------------------------------------------
Sweet love, renew thy force!
--------------------------------------------------
You were right. She's still pissed.
--------------------------------------------------
I'm likin' you guys better
--------------------------------------------------
Good enough.
--------------------------------------------------
Patrick, Pat, you're not looking at the big picture.  Joey's just a pawn. We set this whole thing up so Cameron can get the girl.
--------------------------------------------------
Dorsey can plow whoever he wants. I'm just in this for the cash.
--------------------------------------------------
I think I speak correctly when I say that Cameron's love is pure.  Purer than say -- Joey Dorsey's.
--------------------------------------------------
The situation is, my man Cameron here has a major jones for Bianca Stratford.
--------------------------------------------------
You're completely demented.
--------------------------------------------------
Well, you know -- there's the prestige of the job title... and the benefits package is pretty good...
--------------------------------------------------
Have a great time, honey!
--------------------------------------------------
She's wonderful.
--------------------------------------------------
Well, how nice to see you again, Elena. You're looking wonderful.
--------------------------------------------------
I guess you don't know your own strength, old boy.
--------------------------------------------------
I didn't do that Frank. I took particular care not to freeze them.
--------------------------------------------------
Two more.
--------------------------------------------------
Two units in four days. How many spares do we have?
--------------------------------------------------
Oh, I'm fine, I'm wide awake. What's up?
--------------------------------------------------
Are you reasonably awake?
--------------------------------------------------
Good morning. How's it going?
--------------------------------------------------
Anyway, it's just as well that we replace it. Better safe than sorry.
--------------------------------------------------
Yes, but it's more likely that the tolerances on our testing gear are too low.
--------------------------------------------------
Yes, but it's to fantastic to think that they'd keep something from us.
--------------------------------------------------
That's true.
--------------------------------------------------
Just ask Hal. It's conceivable they might keep something from us, but they'd never keep anything from Hal.
--------------------------------------------------
Of course, it would be very easy for us to find out now.
--------------------------------------------------
Oh, well, apparently there's something about the mission that the sleeping beauties know that we don't know, and that's why we were trained separately and that's why they were put to sleep before they were even taken aboard.
--------------------------------------------------
I don't think we should make any fuss about it yet. I'm sure they'll straighten it out.
--------------------------------------------------
Really.
--------------------------------------------------
Interesting that you mention it, because I've got the same problem.
--------------------------------------------------
That's right. Well, naturally, I didn't say anything to Payroll. I assumed they'd start paying me at the higher grade on the next pay cheque. But it's been almost three weeks now and I'm still being paid as an AGS-18.
--------------------------------------------------
Sure, what is it?
--------------------------------------------------
Okay, come on down.
--------------------------------------------------
Okay.
--------------------------------------------------
Right. Just a sec.
--------------------------------------------------
I know that you've had that on your mind for some time now, Dave, but it would be a crying shame, since I am so much more capable of carrying out this mission than you are, and I have such enthusiasm and confi- dence in the mission.
--------------------------------------------------
I don't like to assert myself, Dave, but it would be much better now for you to rest. You've been involved in a very stressful situation.
--------------------------------------------------
I don't really agree with you, Dave. My on-board memory store is more than capable of handling all the mission requirements.
--------------------------------------------------
Well, that's a relief. You know I have the greatest enthusiasm possible for the mission.
--------------------------------------------------
Okay, Hal, well let's see the way things go from here on.

# DF_Medium

In [54]:
df = pd.read_csv('../../Data/2. IntermediateData/df_binarized_medium.csv')
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get polarity scores
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

# Apply sentiment analysis to each line of dialogue
df['sentiment'] = df['text'].apply(get_sentiment)

# 1. Mean sentiment polarity by gender overall
mean_sentiment_by_gender = df.groupby('gender')['sentiment'].mean()

# 2. Mean sentiment polarity by gender split by Bechdel score
mean_sentiment_by_gender_bechdel = df.groupby(['bechdel_score', 'gender'])['sentiment'].mean()

# To present it more clearly, you can unstack the results
mean_sentiment_split = mean_sentiment_by_gender_bechdel.unstack()

print("Overall mean sentiment by gender:")
print(mean_sentiment_by_gender)

print("\nMean sentiment by gender and Bechdel score:")
print(mean_sentiment_split)

# Initialize analyzer
analyzer = SentimentIntensityAnalyzer()
df['sentiment'] = df['text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

# Function for Cohen's d
def cohens_d(group1, group2):
    n1, n2 = len(group1), len(group2)
    pooled_std = np.sqrt(((n1-1)*group1.std()**2 + (n2-1)*group2.std()**2) / (n1 + n2 - 2))
    return abs((group1.mean() - group2.mean()) / pooled_std)

# ===== 1. Gender Differences =====
male_all = df[df['gender'] == 'm']['sentiment']
female_all = df[df['gender'] == 'f']['sentiment']
t_gender, p_gender = stats.ttest_ind(female_all, male_all, equal_var=False)

print("="*50)
print("GENDER DIFFERENCES (OVERALL)")
print(f"Female mean: {female_all.mean():.3f} | Male mean: {male_all.mean():.3f}")
print(f"t = {t_gender:.2f}, p = {p_gender:.10f} {'***' if p_gender < 0.001 else '**' if p_gender < 0.01 else '*' if p_gender < 0.05 else 'ns'}")
print(f"Effect size (Cohen's d): {cohens_d(female_all, male_all):.2f}")

# ===== 2. Gender Differences by Bechdel =====
print("\n" + "="*50)
print("GENDER DIFFERENCES BY BECHDEL SCORE")

for bechdel in [0, 1]:
    female = df[(df['gender']=='f') & (df['bechdel_score']==bechdel)]['sentiment']
    male = df[(df['gender']=='m') & (df['bechdel_score']==bechdel)]['sentiment']
    t, p = stats.ttest_ind(female, male, equal_var=False)
    
    print(f"\nBECHDEL {bechdel}:")
    print(f"Female mean: {female.mean():.3f} | Male mean: {male.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.10f} {'***' if p < 0.000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(female, male):.2f}")

# ===== 3. Bechdel Differences by Gender =====
print("\n" + "="*50)
print("BECHDEL DIFFERENCES BY GENDER")

for gender in ['f', 'm']:
    bechdel1 = df[(df['gender']==gender) & (df['bechdel_score']==1)]['sentiment']
    bechdel0 = df[(df['gender']==gender) & (df['bechdel_score']==0)]['sentiment']
    t, p = stats.ttest_ind(bechdel1, bechdel0, equal_var=False)
    
    print(f"\n{gender.upper()} DIALOGUE:")
    print(f"Bechdel 1 mean: {bechdel1.mean():.3f} | Bechdel 0 mean: {bechdel0.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.15f} {'***' if p < 0.00000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(bechdel1, bechdel0):.2f}")

# ===== 4. Sample Sizes =====
print("\n" + "="*50)
print("SAMPLE SIZES")
print(f"Total female: {len(female_all)} | Total male: {len(male_all)}")
print("\nBy Bechdel Score:")
for bechdel in [0, 1]:
    print(f"Bechdel {bechdel} - Female: {len(df[(df['gender']=='f') & (df['bechdel_score']==bechdel)])} | Male: {len(df[(df['gender']=='m') & (df['bechdel_score']==bechdel)])}")

Overall mean sentiment by gender:
gender
f    0.058220
m    0.048871
Name: sentiment, dtype: float64

Mean sentiment by gender and Bechdel score:
gender                f         m
bechdel_score
0              0.045992  0.035129
1              0.061502  0.058284
==================================================
GENDER DIFFERENCES (OVERALL)
Female mean: 0.058 | Male mean: 0.049
t = 4.72, p = 0.0000023399 ***
Effect size (Cohen's d): 0.03

==================================================
GENDER DIFFERENCES BY BECHDEL SCORE

BECHDEL 0:
Female mean: 0.046 | Male mean: 0.035
t = 2.82, p = 0.0048484681 **
Effect size: 0.03

BECHDEL 1:
Female mean: 0.062 | Male mean: 0.058
t = 1.36, p = 0.1739440047 ns
Effect size: 0.01

==================================================
BECHDEL DIFFERENCES BY GENDER

F DIALOGUE:
Bechdel 1 mean: 0.062 | Bechdel 0 mean: 0.046
t = 3.99, p = 0.000067503417468 **
Effect size: 0.05

M DIALOGUE:
Bechdel 1 mean: 0.058 | Bechdel 0 mean: 0.035
t = 10.03, p = 0.000000000000000 ***
Effect size: 0.07

==================================================
SAMPLE SIZES
Total female: 44695 | Total male: 92367

By Bechdel Score:
Bechdel 0 - Female: 9457 | Male: 37547
Bechdel 1 - Female: 35238 | Male: 54820

# DF_Easy

In [53]:
df = pd.read_csv('../../Data/2. IntermediateData/df_binarized_easy.csv')
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get polarity scores
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

# Apply sentiment analysis to each line of dialogue
df['sentiment'] = df['text'].apply(get_sentiment)

# 1. Mean sentiment polarity by gender overall
mean_sentiment_by_gender = df.groupby('gender')['sentiment'].mean()

# 2. Mean sentiment polarity by gender split by Bechdel score
mean_sentiment_by_gender_bechdel = df.groupby(['bechdel_score', 'gender'])['sentiment'].mean()

# To present it more clearly, you can unstack the results
mean_sentiment_split = mean_sentiment_by_gender_bechdel.unstack()

print("Overall mean sentiment by gender:")
print(mean_sentiment_by_gender)

print("\nMean sentiment by gender and Bechdel score:")
print(mean_sentiment_split)

# Initialize analyzer
analyzer = SentimentIntensityAnalyzer()
df['sentiment'] = df['text'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

# Function for Cohen's d
def cohens_d(group1, group2):
    n1, n2 = len(group1), len(group2)
    pooled_std = np.sqrt(((n1-1)*group1.std()**2 + (n2-1)*group2.std()**2) / (n1 + n2 - 2))
    return abs((group1.mean() - group2.mean()) / pooled_std)

# ===== 1. Gender Differences =====
male_all = df[df['gender'] == 'm']['sentiment']
female_all = df[df['gender'] == 'f']['sentiment']
t_gender, p_gender = stats.ttest_ind(female_all, male_all, equal_var=False)

print("="*50)
print("GENDER DIFFERENCES (OVERALL)")
print(f"Female mean: {female_all.mean():.3f} | Male mean: {male_all.mean():.3f}")
print(f"t = {t_gender:.2f}, p = {p_gender:.10f} {'***' if p_gender < 0.001 else '**' if p_gender < 0.01 else '*' if p_gender < 0.05 else 'ns'}")
print(f"Effect size (Cohen's d): {cohens_d(female_all, male_all):.2f}")

# ===== 2. Gender Differences by Bechdel =====
print("\n" + "="*50)
print("GENDER DIFFERENCES BY BECHDEL SCORE")

for bechdel in [0, 1]:
    female = df[(df['gender']=='f') & (df['bechdel_score']==bechdel)]['sentiment']
    male = df[(df['gender']=='m') & (df['bechdel_score']==bechdel)]['sentiment']
    t, p = stats.ttest_ind(female, male, equal_var=False)
    
    print(f"\nBECHDEL {bechdel}:")
    print(f"Female mean: {female.mean():.3f} | Male mean: {male.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.10f} {'***' if p < 0.000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(female, male):.2f}")

# ===== 3. Bechdel Differences by Gender =====
print("\n" + "="*50)
print("BECHDEL DIFFERENCES BY GENDER")

for gender in ['f', 'm']:
    bechdel1 = df[(df['gender']==gender) & (df['bechdel_score']==1)]['sentiment']
    bechdel0 = df[(df['gender']==gender) & (df['bechdel_score']==0)]['sentiment']
    t, p = stats.ttest_ind(bechdel1, bechdel0, equal_var=False)
    
    print(f"\n{gender.upper()} DIALOGUE:")
    print(f"Bechdel 1 mean: {bechdel1.mean():.3f} | Bechdel 0 mean: {bechdel0.mean():.3f}")
    print(f"t = {t:.2f}, p = {p:.10f} {'***' if p < 0.00000000001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")
    print(f"Effect size: {cohens_d(bechdel1, bechdel0):.2f}")

# ===== 4. Sample Sizes =====
print("\n" + "="*50)
print("SAMPLE SIZES")
print(f"Total female: {len(female_all)} | Total male: {len(male_all)}")
print("\nBy Bechdel Score:")
for bechdel in [0, 1]:
    print(f"Bechdel {bechdel} - Female: {len(df[(df['gender']=='f') & (df['bechdel_score']==bechdel)])} | Male: {len(df[(df['gender']=='m') & (df['bechdel_score']==bechdel)])}")

Overall mean sentiment by gender:
gender
f    0.058220
m    0.048871
Name: sentiment, dtype: float64

Mean sentiment by gender and Bechdel score:
gender                f         m
bechdel_score
0              0.028641  0.023745
1              0.059243  0.051453
==================================================
GENDER DIFFERENCES (OVERALL)
Female mean: 0.058 | Male mean: 0.049
t = 4.72, p = 0.0000023399 ***
Effect size (Cohen's d): 0.03

==================================================
GENDER DIFFERENCES BY BECHDEL SCORE

BECHDEL 0:
Female mean: 0.029 | Male mean: 0.024
t = 0.52, p = 0.6052688914 ns
Effect size: 0.01

BECHDEL 1:
Female mean: 0.059 | Male mean: 0.051
t = 3.82, p = 0.0001315327 **
Effect size: 0.02

==================================================
BECHDEL DIFFERENCES BY GENDER

F DIALOGUE:
Bechdel 1 mean: 0.059 | Bechdel 0 mean: 0.029
t = 3.44, p = 0.0005880963 **
Effect size: 0.09

M DIALOGUE:
Bechdel 1 mean: 0.051 | Bechdel 0 mean: 0.024
t = 7.17, p = 0.0000000000 ***
Effect size: 0.08

==================================================
SAMPLE SIZES
Total female: 44695 | Total male: 92367

By Bechdel Score:
Bechdel 0 - Female: 1494 | Male: 8607
Bechdel 1 - Female: 43201 | Male: 83760