# Imports

In [14]:
#install Vader through "pip install vaderSentiment" in terminal
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
df = pd.read_csv('../../Data/2. IntermediateData/df_binarized_hard.csv')

In [15]:
df

,utterance_id,conversation_id,text,speaker,movie_id,reply_to,speaker_id,character_name,movie_id.1,title,...,credit_pos,year,id,imdbid,bechdel_score,imdb_score,numVotes,runtimeMinutes,genres,oscar
0,L1045,L1044,They do not!,u0,m0,L1044,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
1,L1044,L1044,They do to!,u2,m0,NaN,u2,CAMERON,m0,10 things i hate about you,...,3,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
2,L985,L984,I hope so.,u0,m0,L984,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
3,L984,L984,She okay?,u2,m0,NaN,u2,CAMERON,m0,10 things i hate about you,...,3,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
4,L925,L924,Let's go.,u0,m0,L924,u0,BIANCA,m0,10 things i hate about you,...,4,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137057,L665991,L665987,"I'm sorry, sir. We only seat by reservation.",u9021,m615,L665990,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137058,L665990,L665987,Food!!,u9023,m615,L665989,u9023,MONSTER,m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137059,L665989,L665987,Do you have a reservation?,u9021,m615,L665988,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137060,L665988,L665987,Food!,u9023,m615,L665987,u9023,MONSTER,m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0
137061,L665987,L665987,"Yes, sir, name, please?",u9021,m615,NaN,u9021,MAITRE D',m615,young frankenstein,...,?,1974,1077,72431,0,8.0,176404,106,Comedy,0

In [16]:
df=df.drop(['movie_id.1'], axis=1)

# Calculating sentiment score with VADER

In [17]:
# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Function to get polarity scores
def get_sentiment(text):
    return analyzer.polarity_scores(text)['compound']

# Apply sentiment analysis to each line of dialogue
df['sentiment'] = df['text'].apply(get_sentiment)

# 1. Mean sentiment polarity by gender overall
mean_sentiment_by_gender = df.groupby('gender')['sentiment'].mean()

# 2. Mean sentiment polarity by gender split by Bechdel score
mean_sentiment_by_gender_bechdel = df.groupby(['bechdel_score', 'gender'])['sentiment'].mean()

# To present it more clearly, you can unstack the results
mean_sentiment_split = mean_sentiment_by_gender_bechdel.unstack()

print("Overall mean sentiment by gender:")
print(mean_sentiment_by_gender)

print("\nMean sentiment by gender and Bechdel score:")
print(mean_sentiment_split)

Overall mean sentiment by gender:
gender
f    0.058220
m    0.048871
Name: sentiment, dtype: float64

Mean sentiment by gender and Bechdel score:
gender                f         m
bechdel_score
0              0.058090  0.044079
1              0.058289  0.055099

In [18]:
df

,utterance_id,conversation_id,text,speaker,movie_id,reply_to,speaker_id,character_name,title,gender,...,year,id,imdbid,bechdel_score,imdb_score,numVotes,runtimeMinutes,genres,oscar,sentiment
0,L1045,L1044,They do not!,u0,m0,L1044,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
1,L1044,L1044,They do to!,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
2,L985,L984,I hope so.,u0,m0,L984,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.4404
3,L984,L984,She okay?,u2,m0,NaN,u2,CAMERON,10 things i hate about you,m,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.2263
4,L925,L924,Let's go.,u0,m0,L924,u0,BIANCA,10 things i hate about you,f,...,1999,374,147800,1,7.4,424659,97,"Comedy,Drama,Romance",0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137057,L665991,L665987,"I'm sorry, sir. We only seat by reservation.",u9021,m615,L665990,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,-0.0772
137058,L665990,L665987,Food!!,u9023,m615,L665989,u9023,MONSTER,young frankenstein,m,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137059,L665989,L665987,Do you have a reservation?,u9021,m615,L665988,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137060,L665988,L665987,Food!,u9023,m615,L665987,u9023,MONSTER,young frankenstein,m,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.0000
137061,L665987,L665987,"Yes, sir, name, please?",u9021,m615,NaN,u9021,MAITRE D',young frankenstein,f,...,1974,1077,72431,0,8.0,176404,106,Comedy,0,0.6124

In [24]:
# Categorize sentiment first
df['sentiment_category'] = df['sentiment'].apply(
    lambda x: 'Positive' if x >= 0.05 
    else 'Negative' if x <= -0.05 
    else 'Neutral'
)

# Print text for each category
print("="*50 + "\nFIRST 40 POSITIVE TEXTS\n" + "="*50)
for text in df[df['sentiment_category'] == 'Positive']['text'].head(100):
    print(text)
    print("-"*50)  # Separator between entries

print("\n" + "="*50 + "\nFIRST 40 NEUTRAL TEXTS\n" + "="*50) 
for text in df[df['sentiment_category'] == 'Neutral']['text'].head(40):
    print(text)
    print("-"*50)

print("\n" + "="*50 + "\nFIRST 40 NEGATIVE TEXTS\n" + "="*50)
for text in df[df['sentiment_category'] == 'Negative']['text'].head(40):
    print(text)
    print("-"*50)

==================================================
FIRST 40 POSITIVE TEXTS
==================================================
I hope so.
--------------------------------------------------
She okay?
--------------------------------------------------
Wow
--------------------------------------------------
Okay -- you're gonna need to learn how to lie.
--------------------------------------------------
I'm kidding.  You know how sometimes you just become this "persona"?  And you don't know how to quit?
--------------------------------------------------
What good stuff?
--------------------------------------------------
I figured you'd get to the good stuff eventually.
--------------------------------------------------
Thank God!  If I had to hear one more story about your coiffure...
--------------------------------------------------
Me.  This endless ...blonde babble. I'm like, boring myself.
--------------------------------------------------
Then Guillermo says, "If you go any lighter, you're gonna look like an extra on 90210."
--------------------------------------------------
Well, no...
--------------------------------------------------
I looked for you back at the party, but you always seemed to be "occupied".
--------------------------------------------------
Have fun tonight?
--------------------------------------------------
I believe we share an art instructor
--------------------------------------------------
Looks like things worked out tonight, huh?
--------------------------------------------------
So that's the kind of guy she likes? Pretty ones?
--------------------------------------------------
Lesbian?  No. I found a picture of Jared Leto in one of her drawers, so I'm pretty sure she's not harboring same-sex tendencies.
--------------------------------------------------
Sure have.
--------------------------------------------------
How do you get your hair to look like that?
--------------------------------------------------
You're sweet.
--------------------------------------------------
Well, there's someone I think might be --
--------------------------------------------------
That's because it's such a nice one.
--------------------------------------------------
I don't want to know how to say that though.  I want to know useful things. Like where the good stores are.  How much does champagne cost?  Stuff like Chat.  I have never in my life had to point out my head to someone.
--------------------------------------------------
Right.  See?  You're ready for the quiz.
--------------------------------------------------
Unsolved mystery.  She used to be really popular when she started high school, then it was just like she got sick of it or something.
--------------------------------------------------
Seems like she could get a date easy enough...
--------------------------------------------------
You're asking me out.  That's so cute. What's your name again?
--------------------------------------------------
Okay... then how 'bout we try out some French cuisine.  Saturday?  Night?
--------------------------------------------------
Not the hacking and gagging and spitting part.  Please.
--------------------------------------------------
Well, I thought we'd start with pronunciation, if that's okay with you.
--------------------------------------------------
All I know is -- I'd give up my private line to go out with a guy like Joey.
--------------------------------------------------
Sometimes I wonder if the guys we're supposed to want to go out with are the ones we actually want to go out with, you know?
--------------------------------------------------
Great
--------------------------------------------------
Listen, I want to talk to you about the prom.
--------------------------------------------------
Hey, sweet cheeks.
--------------------------------------------------
My agent says I've got a good shot at being the Prada guy next year.
--------------------------------------------------
Neat...
--------------------------------------------------
It's a gay cruise line, but I'll be, like, wearing a uniform and stuff.
--------------------------------------------------
So yeah, I've got the Sears catalog thing going -- and the tube sock gig " that's gonna be huge.  And then I'm up for an ad for Queen Harry next week.
--------------------------------------------------
Hopefully.
--------------------------------------------------
You looked beautiful last night, you know.
--------------------------------------------------
Not all experiences are good, Bianca. You can't always trust the people you want to.
--------------------------------------------------
God, you're just like him! Just keep me locked away in the dark, so I can't experience anything for myself
--------------------------------------------------
I'm not stupid enough to repeat your mistakes.
--------------------------------------------------
No. you didn't!  If you really thought I could make my own decisions, you would've let me go out with him instead of helping Daddy hold me hostage.
--------------------------------------------------
After that, I swore I'd never do anything just because "everyone else" was doing it.  And I haven't since. Except for Bogey's party, and my stunning gastro-intestinal display --
--------------------------------------------------
He was, like, a total babe
--------------------------------------------------
I wish I had that luxury. I'm the only sophomore that got asked to the prom and I can't go, because you won ' t.
--------------------------------------------------
I do care. But I'm a firm believer in doing something for your own reasons, not someone else ' s .
--------------------------------------------------
Like you care.
--------------------------------------------------
You're welcome.
--------------------------------------------------
I don't get you.  You act like you're too good for any of this, and then you go totally apeshit when you get here.
--------------------------------------------------
Like I'm supposed to know what that even means.
--------------------------------------------------
Can't you forget for just one night that you're completely wretched?
--------------------------------------------------
Oh, I thought you might have a date  I don't know why I'm bothering to ask, but are you going to Bogey Lowenstein's party Saturday night?
--------------------------------------------------
It means that Gigglepuss is playing at Club Skunk and we're going.
--------------------------------------------------
Oh my God, does this mean you're becoming normal?
--------------------------------------------------
I have a date, Daddy.  And he ' s not a captain of oppression like some men we know.
--------------------------------------------------
It's that hot rod Joey, right? That ' s who you want me to bend my rules for?
--------------------------------------------------
Daddy, I want to discuss the prom with you. It's tomorrow night --
--------------------------------------------------
Promise me you won't talk to any boys unless your sister is present.
--------------------------------------------------
It's just a party. Daddy.
--------------------------------------------------
Oh, God.  It's starting.
--------------------------------------------------
If you must know, we were attempting to go to a small study group of friends.
--------------------------------------------------
Now don't get upset. Daddy, but there's this boy... and I think he might ask...
--------------------------------------------------
Fan of a fan.  You see a couple of minors come in?
--------------------------------------------------
Didn't have you pegged for a Gigglepuss fan.  Aren't they a little too pre-teen belly-button ring for you?
--------------------------------------------------
Always a pleasure, Brucie.
--------------------------------------------------
Best case scenario, you're back on the payroll for awhile.
--------------------------------------------------
You humiliated the woman! Sacrifice yourself on the altar of dignity and even the score.
--------------------------------------------------
Buttholus extremus.  But hey, you're making progress.
--------------------------------------------------
It's her favorite band.
--------------------------------------------------
He's pretty!
--------------------------------------------------
Her favorite uncle
--------------------------------------------------
Are you kidding?  He'll piss himself with joy.  He's the ultimate kiss ass.
--------------------------------------------------
This is it.  A golden opportunity. Patrick can ask Katarina to the party.
--------------------------------------------------
They always let felons sit in on Honors Biology?
--------------------------------------------------
I teach her French, get to know her, dazzle her with charm and she falls in love with me.
--------------------------------------------------
Yeah, just a minor encounter with the shrew.
--------------------------------------------------
You could consecrate with her, my friend.
--------------------------------------------------
You mean I'd get a chance to talk to her?
--------------------------------------------------
Sure do ... my Mom's from Canada
--------------------------------------------------
Joey Dorsey?  Perma-shit-grin.  I wish I could say he's a moron, but he's number twelve in the class.  And a model.  Mostly regional stuff, but he's rumored to have a big tube sock ad coming out.
--------------------------------------------------
He always have that shit-eating grin?
--------------------------------------------------
Because they're bred to.  Their mothers liked guys like that, and their grandmothers before them. Their gene pool is rarely diluted.
--------------------------------------------------
Why do girls like that always like guys like that?
--------------------------------------------------
Yeah, but these guys have never seen a horse.  They just jack off to Clint Eastwood.
--------------------------------------------------
Yeah.  A couple.  We're outnumbered by the cows, though.
--------------------------------------------------
I was kidding. People actually live there?
--------------------------------------------------
She kissed me.
--------------------------------------------------
She just needs time to cool off I'll give it a day.
--------------------------------------------------
Sure
--------------------------------------------------
Cameron -- do you like the girl?
--------------------------------------------------
Gigglepuss is playing there tomorrow night.
--------------------------------------------------
I've retrieved certain pieces of information on Miss Katarina Stratford I think you'll find helpful.
--------------------------------------------------
Yeah -- we'll see.
--------------------------------------------------
Yeah, and I noticed the only part of you featured in your big Kmart spread was your elbow.  Tough break.
--------------------------------------------------
Get her to act like a human
--------------------------------------------------
Fine, thirty.
--------------------------------------------------
I can't take a girl like that out on twenty bucks.
--------------------------------------------------

==================================================
FIRST 40 NEUTRAL TEXTS
==================================================
They do not!
--------------------------------------------------
They do to!
--------------------------------------------------
Let's go.
--------------------------------------------------
The "real you".
--------------------------------------------------
No...
--------------------------------------------------
But
--------------------------------------------------
Then that's all you had to say.
--------------------------------------------------
You never wanted to go out with 'me, did you?
--------------------------------------------------
I was?
--------------------------------------------------
Tons
--------------------------------------------------
You know Chastity?
--------------------------------------------------
Hi.
--------------------------------------------------
Who knows?  All I've ever heard her say is that she'd dip before dating a guy that smokes.
--------------------------------------------------
She's not a...
--------------------------------------------------
I'm workin' on it. But she doesn't seem to be goin' for him.
--------------------------------------------------
I really, really, really wanna go, but I can't.  Not unless my sister goes.
--------------------------------------------------
You have my word.  As a gentleman
--------------------------------------------------
You got something on your mind?
--------------------------------------------------
Where?
--------------------------------------------------
There.
--------------------------------------------------
How is our little Find the Wench A Date plan progressing?
--------------------------------------------------
C'esc ma tete. This is my head
--------------------------------------------------
Let me see what I can do.
--------------------------------------------------
Gosh, if only we could find Kat a boyfriend...
--------------------------------------------------
Why?
--------------------------------------------------
Cameron.
--------------------------------------------------
I did.
--------------------------------------------------
You think you ' re the only sophomore at the prom?
--------------------------------------------------
I don't have to be home 'til two.
--------------------------------------------------
I have to be home in twenty minutes.
--------------------------------------------------
Bianca, I don't think the highlights of dating Joey Dorsey are going to include door-opening and coat-holding.
--------------------------------------------------
Combination.  I don't know -- I thought he'd be different.  More of a gentleman...
--------------------------------------------------
Is he oily or dry?
--------------------------------------------------
Would you mind getting me a drink, Cameron?
--------------------------------------------------
Joey.
--------------------------------------------------
Who?
--------------------------------------------------
Where did he go?  He was just here.
--------------------------------------------------
You might wanna think about it
--------------------------------------------------
No.
--------------------------------------------------
Did you change your hair?
--------------------------------------------------

==================================================
FIRST 40 NEGATIVE TEXTS
==================================================
No
--------------------------------------------------
Like my fear of wearing pastels?
--------------------------------------------------
What crap?
--------------------------------------------------
do you listen to this crap?
--------------------------------------------------
You always been this selfish?
--------------------------------------------------
Eber's Deep Conditioner every two days. And I never, ever use a blowdryer without the diffuser attachment.
--------------------------------------------------
I counted on you to help my cause. You and that thug are obviously failing. Aren't we ever going on our date?
--------------------------------------------------
Forget French.
--------------------------------------------------
That's a shame.
--------------------------------------------------
The thing is, Cameron -- I'm at the mercy of a particularly hideous breed of loser.  My sister.  I can't date until she does.
--------------------------------------------------
No, no, it's my fault -- we didn't have a proper introduction ---
--------------------------------------------------
Forget it.
--------------------------------------------------
Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.
--------------------------------------------------
He practically proposed when he found out we had the same dermatologist. I mean. Dr. Bonchowski is great an all, but he's not exactly relevant party conversation.
--------------------------------------------------
You're concentrating awfully hard considering it's gym class.
--------------------------------------------------
What? To completely damage me?  To send me to therapy forever? What?
--------------------------------------------------
Just once.  Afterwards, I told him I didn't want to anymore.  I wasn't ready. He got pissed.  Then he broke up with me.
--------------------------------------------------
But you hate Joey
--------------------------------------------------
Listen, I know you hate having to sit home because I'm not Susie High School.
--------------------------------------------------
Yeah, he's your freak friend Mandella's boyfriend.  I guess since I'm not allowed to go out, I should obsess over a dead guy, too.
--------------------------------------------------
At least I'm not a clouted fen- sucked hedge-pig.
--------------------------------------------------
Bogey Lowenstein's party is normal, but you're too busy listening to Bitches Who Need Prozac to know that.
--------------------------------------------------
You're ruining my life'  Because you won't be normal, I can't be normal.
--------------------------------------------------
I think you're a freak.  I think you do this to torture me.  And I think you suck.
--------------------------------------------------
I have the potential to smack the crap out of you if you don't get out of my way.
--------------------------------------------------
I'm missing something.
--------------------------------------------------
Fine.  I see that I'm a prisoner in my own house.  I'm not a daughter. I'm a possession!
--------------------------------------------------
Because she'll scare them away.
--------------------------------------------------
It's just a party. Daddy, but I knew you'd forbid me to go since "Gloria Steinem" over there isn't going --
--------------------------------------------------
But she doesn't want to date.
--------------------------------------------------
But it's not fair -- she's a mutant, Daddy!
--------------------------------------------------
The hell is that?  What kind of 'guy just picks up a girl and carries her away while you're talking to her?
--------------------------------------------------
Extremely unfortunate maneuver.
--------------------------------------------------
Hell, I've just been going over the whole thing in my head and -
--------------------------------------------------
Okay!  I wasn't sure
--------------------------------------------------
Dead at forty-one.
--------------------------------------------------
It's a lung cancer issue
--------------------------------------------------
Number one.  She hates smokers
--------------------------------------------------
Like we had a choice?  Besides -- when you let the enemy think he's orchestrating the battle, you're in a position of power. We let him pretend he's calling the shots, and while he's busy setting up the plan, you have time to woo Bianca.
--------------------------------------------------
I thought you hated those people.
--------------------------------------------------